---
title: "Mini project 4"
author: "By: Greta Mundt, Talia Seshaiah and Sonia Garfinkel"
output: html_document
---

```{r message = FALSE}
library(mdsr)
library(RMySQL)
library(dplyr)
library(babynames)
```

```{r}
db <- dbConnect_scidb(dbname = "imdb")
class(db)
```

```{r}
db %>%
  dbGetQuery("SELECT *
             FROM title
             WHERE kind_id = 1
             AND production_year >= 2008 AND production_year <= 2018
             ORDER BY production_year DESC;")

```


```{r}
decade_movie <- db %>% 
  dbGetQuery("SELECT id, title, kind_id, production_year
             FROM title
             WHERE kind_id = '1'
             AND production_year >= 2008 AND production_year <= 2018
             ORDER BY production_year desc;")

f_director <- db %>%
  dbGetQuery("SELECT n.name, n.gender, ci.role_id, ci.person_id, ci.movie_id
             FROM cast_info ci
             JOIN name n ON n.id = ci.person_id
             WHERE ci.role_id = '8'
             AND n.gender = 'f';")

m_director <- db %>%
  dbGetQuery("SELECT n.name, n.gender, ci.role_id, ci.person_id, ci.movie_id
             FROM cast_info ci
             JOIN name n ON n.id = ci.person_id
             WHERE ci.role_id = '8'
             AND n.gender = 'm';")
```


###Joining tables to get our "final" data set/table
```{r}
f_director2 <- f_director %>%
  inner_join(decade_movie, by = c("movie_id" = "id"))
 
m_director2 <- m_director %>%
  inner_join(decade_movie, by = c("movie_id" = "id"))
  
```

```{r}
f_director_count <- f_director2 %>%
  filter(gender == "f") %>%
  group_by(production_year) %>%
  summarize(N = n())

director_count<- director %>%
  filter()%>%
  group_by(production_year)%>%
  summarize(N = n())
```
```{r}
ggplot(f_director_count, aes(x = production_year, y = N)) + 
  geom_line()
                          
```


```{r}
babynames %>%
  filter(name == "Jackie") %>%
  group_by(year) %>%
  summarize(N = n(), 
            total = sum(n), 
            boys = sum(ifelse(sex == "M", n, 0)))
```







###Our graph
```{r}
director <- rbind(f_director2, m_director2)

director2 <- director%>%
  arrange(desc(production_year)) %>%
  mutate(sum = count(n))
  
  
  filter(gender == "f", production_year == 2015) %>%
  summarize(num_rows = n(), = max(n))

director %>%
  group_by(production_year, gender) %>%
  arrange(desc(production_year))
  mutate(count = n())



ggplot(director, aes(x = production_year, y = gender)) + 
  geom_line()
                                                   
                                                   
```

